librarium/Models/Librarian.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace librarium.Models
{
    public class Librarian
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "Name is required!")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Surname is required!")]
        public string Surname { get; set; }

        public string Address { get; set; }

        [Required(ErrorMessage = "Phone number is required!")]
        [Display(Name = "Phone number")]
        [RegularExpression(@"^((\+389) [2] \d{4} \d{3})|^((\+389) [7][0125678] \d{3} \d{3})$|^((\+389) [4][2345678] \d{3} \d{3})$|^((\+389) [3][1234] \d{3} \d{3})$", ErrorMessage ="Please enter valid phone number!")]
        public string PhoneNumber { get; set; }

        [Required(ErrorMessage = "Personal number is required!")]
        [Display(Name = "Personal number")]
        [RegularExpression(@"^\d{13}$", ErrorMessage = "Please enter valid personal number!")]
        public string PersonalNumber { get; set; }

        [Required(ErrorMessage = "Bank account number is required!")]
        [Display(Name = "Bank account number")]
        [RegularExpression(@"^\d{3}-\d{10}-\d{2}$", ErrorMessage ="Please enter valid bank account number!")]
        public string BankAccountNumber { get; set; }

        public string Education { get; set; }

        [Display(Name = "Date of employment")]
        public string DateOfEmployment { get; set; }
    }
}

librarium/Controllers/LibrariansController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using librarium.Models;

namespace librarium.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class LibrariansController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        //[Authorize(Roles = "Administrator, Employee")]
        // GET: Librarians
        public ActionResult Index()
        {
            return View(db.Librarians.ToList());
        }

        //[Authorize(Roles = "Administrator, Employee")]
        // GET: Librarians/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Librarian librarian = db.Librarians.Find(id);
            if (librarian == null)
            {
                return HttpNotFound();
            }
            return View(librarian);
        }

        //[Authorize(Roles = "Administrator, Employee")]
        // GET: Librarians/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Librarians/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        //[Authorize(Roles = "Administrator, Employee")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Surname,Address,PhoneNumber,PersonalNumber,BankAccountNumber,Education,DateOfEmployment")] Librarian librarian)
        {
            if (ModelState.IsValid)
            {
                db.Librarians.Add(librarian);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(librarian);
        }

        //[Authorize(Roles = "Administrator, Employee")]
        // GET: Librarians/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Librarian librarian = db.Librarians.Find(id);
            if (librarian == null)
            {
                return HttpNotFound();
            }
            return View(librarian);
        }

        // POST: Librarians/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        //[Authorize(Roles = "Administrator, Employee")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Surname,Address,PhoneNumber,PersonalNumber,BankAccountNumber,Education,DateOfEmployment")] Librarian librarian)
        {
            if (ModelState.IsValid)
            {
                db.Entry(librarian).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(librarian);
        }

        /*
        // GET: Librarians/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Librarian librarian = db.Librarians.Find(id);
            if (librarian == null)
            {
                return HttpNotFound();
            }
            return View(librarian);
        }
        */


        /*
        // POST: Librarians/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)

        */
        //[Authorize(Roles = "Administrator")]
        public ActionResult Delete(int id)
        {
            Librarian librarian = db.Librarians.Find(id);
            db.Librarians.Remove(librarian);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

librarium/Views/Librarians/Create.cshtml
<link href="@Url.Content("~/Content/font.css")" rel="stylesheet" type="text/css" />

@model librarium.Models.Librarian

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Librarian</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Surname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Surname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Surname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PersonalNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PersonalNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PersonalNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BankAccountNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BankAccountNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BankAccountNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Education, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Education, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Education, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateOfEmployment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateOfEmployment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateOfEmployment, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", "Librarians", htmlAttributes: new { @class = "btn btn-default" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

librarium/Views/Librarians/Delete.cshtml
<link href="@Url.Content("~/Content/font.css")" rel="stylesheet" type="text/css" />

@model librarium.Models.Librarian

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Librarian</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Surname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Surname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PersonalNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PersonalNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BankAccountNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BankAccountNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Education)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Education)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateOfEmployment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateOfEmployment)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

librarium/Views/Librarians/Details.cshtml
<link href="@Url.Content("~/Content/font.css")" rel="stylesheet" type="text/css" />

@model librarium.Models.Librarian

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Librarian</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Surname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Surname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PersonalNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PersonalNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BankAccountNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BankAccountNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Education)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Education)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateOfEmployment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateOfEmployment)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }, htmlAttributes: new { @class = "btn btn-default" }) 
    @Html.ActionLink("Back to List", "Index", "Librarians", htmlAttributes: new { @class = "btn btn-default" })
</p>

librarium/Views/Librarians/Edit.cshtml
<link href="@Url.Content("~/Content/font.css")" rel="stylesheet" type="text/css" />

@model librarium.Models.Librarian

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Librarian</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Surname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Surname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Surname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PersonalNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PersonalNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PersonalNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BankAccountNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BankAccountNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BankAccountNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Education, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Education, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Education, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateOfEmployment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateOfEmployment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateOfEmployment, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", "Librarians", htmlAttributes: new { @class = "btn btn-default" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

librarium/Views/Librarians/Index.cshtml
<link href="@Url.Content("~/Content/font.css")" rel="stylesheet" type="text/css" />

@model IEnumerable<librarium.Models.Librarian>

@{
    ViewBag.Title = "Librarians";
}

<h2>List of librarians</h2>

<p>
    @Html.ActionLink("Add librarian", "Create", "Librarians", htmlAttributes: new { @class = "btn btn-success" })
</p>
<table id="librariansDatatable" class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Surname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PhoneNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PersonalNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BankAccountNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Education)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateOfEmployment)
            </th>
            <th></th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Surname)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Address)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PhoneNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PersonalNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BankAccountNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Education)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateOfEmployment)
                </td>
                <td>
                    @if (User.IsInRole("Administrator"))
                    {
                        @Html.ActionLink("Edit", "Edit", new { id = item.Id }, htmlAttributes: new { @class = "btn btn-default" })
                        @Html.ActionLink("Details", "Details", new { id = item.Id }, htmlAttributes: new { @class = "btn btn-default" })
                    }



                    @if (User.IsInRole("Administrator"))
                    {
                        <button data-librarian-id="@item.Id" class="button-link js-delete btn btn-danger">Delete</button>
                    }

                    <!-- @Html.ActionLink("Delete", "Delete", new { id = item.Id }) -->
                </td>
            </tr>
        }
    </tbody>
</table>

@section scripts{

    <script>
        $(document).ready(function () {
            var table = $("#librariansDatatable").DataTable();

            $("#librariansDatatable .js-delete").on("click", function () {
                var button = $(this);
                bootbox.confirm("Do you want to delete this librarian?", function (result) {
                    if (result) {
                        $.ajax({
                            url: "/Librarians/Delete/" + button.attr("data-librarian-id"),
                            method: "GET",
                            success: function () {
                                table.row(button.parents("tr")).remove().draw();
                            },
                            error: function (err) {
                                console.log(err);
                            }
                        });
                    }

                });

            });

        });
    </script>

}